/* ══════════════════════════════════════════════════
   LIDL PLU LEARN — PRODUCT DATA
   All PLU codes are illustrative training numbers.
   ══════════════════════════════════════════════════ */

const CATEGORIES = [
  { id: 'fruits',    name: 'Fruits',      emoji: '🍎', color: '#e3000f' },
  { id: 'veggies',   name: 'Vegetables',  emoji: '🥦', color: '#22c55e' },
  { id: 'bakery',    name: 'Bakery',      emoji: '🥖', color: '#f59e0b' },
  { id: 'dairy',     name: 'Dairy',       emoji: '🥛', color: '#06b6d4' },
  { id: 'meat',      name: 'Meat',        emoji: '🥩', color: '#dc2626' },
  { id: 'deli',      name: 'Deli',        emoji: '🧀', color: '#8b5cf6' },
  { id: 'frozen',    name: 'Frozen',      emoji: '🧊', color: '#0ea5e9' },
  { id: 'snacks',    name: 'Snacks',      emoji: '🍫', color: '#78716c' },
];

const PRODUCTS = [
  /* ── FRUITS ── */
  { id: 1,  name: 'Apple (Red)',        plu: '3001', emoji: '🍎', cat: 'fruits'  },
  { id: 2,  name: 'Apple (Green)',      plu: '3002', emoji: '🍏', cat: 'fruits'  },
  { id: 3,  name: 'Banana',             plu: '4011', emoji: '🍌', cat: 'fruits'  },
  { id: 4,  name: 'Orange',             plu: '3107', emoji: '🍊', cat: 'fruits'  },
  { id: 5,  name: 'Strawberry',         plu: '3086', emoji: '🍓', cat: 'fruits'  },
  { id: 6,  name: 'Grapes (Red)',       plu: '4023', emoji: '🍇', cat: 'fruits'  },
  { id: 7,  name: 'Grapes (White)',     plu: '4024', emoji: '🍇', cat: 'fruits'  },
  { id: 8,  name: 'Watermelon',         plu: '3421', emoji: '🍉', cat: 'fruits'  },
  { id: 9,  name: 'Pineapple',          plu: '3141', emoji: '🍍', cat: 'fruits'  },
  { id: 10, name: 'Mango',              plu: '3114', emoji: '🥭', cat: 'fruits'  },
  { id: 11, name: 'Peach',              plu: '3035', emoji: '🍑', cat: 'fruits'  },
  { id: 12, name: 'Pear',               plu: '4416', emoji: '🍐', cat: 'fruits'  },
  { id: 13, name: 'Lemon',              plu: '4053', emoji: '🍋', cat: 'fruits'  },
  { id: 14, name: 'Lime',               plu: '4298', emoji: '🍈', cat: 'fruits'  },
  { id: 15, name: 'Blueberry',          plu: '3447', emoji: '🫐', cat: 'fruits'  },
  { id: 16, name: 'Raspberry',          plu: '3085', emoji: '🍓', cat: 'fruits'  },
  { id: 17, name: 'Kiwi',               plu: '3279', emoji: '🥝', cat: 'fruits'  },
  { id: 18, name: 'Avocado',            plu: '4046', emoji: '🥑', cat: 'fruits'  },
  { id: 19, name: 'Cherry',             plu: '3046', emoji: '🍒', cat: 'fruits'  },
  { id: 20, name: 'Melon (Honeydew)',   plu: '3310', emoji: '🍈', cat: 'fruits'  },
  { id: 21, name: 'Plum',               plu: '3368', emoji: '🟣', cat: 'fruits'  },
  { id: 22, name: 'Apricot',            plu: '3040', emoji: '🍑', cat: 'fruits'  },
  { id: 23, name: 'Pomegranate',        plu: '3490', emoji: '🍎', cat: 'fruits'  },
  { id: 24, name: 'Clementine',         plu: '3487', emoji: '🍊', cat: 'fruits'  },
  { id: 25, name: 'Coconut',            plu: '4196', emoji: '🥥', cat: 'fruits'  },

  /* ── VEGETABLES ── */
  { id: 26, name: 'Broccoli',           plu: '3082', emoji: '🥦', cat: 'veggies' },
  { id: 27, name: 'Carrot',             plu: '3257', emoji: '🥕', cat: 'veggies' },
  { id: 28, name: 'Cucumber',           plu: '4062', emoji: '🥒', cat: 'veggies' },
  { id: 29, name: 'Tomato',             plu: '3145', emoji: '🍅', cat: 'veggies' },
  { id: 30, name: 'Potato',             plu: '4072', emoji: '🥔', cat: 'veggies' },
  { id: 31, name: 'Onion (Yellow)',     plu: '4093', emoji: '🧅', cat: 'veggies' },
  { id: 32, name: 'Onion (Red)',        plu: '3228', emoji: '🧅', cat: 'veggies' },
  { id: 33, name: 'Garlic',             plu: '4608', emoji: '🧄', cat: 'veggies' },
  { id: 34, name: 'Bell Pepper (Red)',  plu: '3002', emoji: '🫑', cat: 'veggies' },
  { id: 35, name: 'Bell Pepper (Grn)', plu: '3004', emoji: '🫑', cat: 'veggies' },
  { id: 36, name: 'Spinach',            plu: '3151', emoji: '🥬', cat: 'veggies' },
  { id: 37, name: 'Lettuce (Iceberg)', plu: '4081', emoji: '🥬', cat: 'veggies' },
  { id: 38, name: 'Corn',               plu: '4959', emoji: '🌽', cat: 'veggies' },
  { id: 39, name: 'Zucchini',           plu: '4067', emoji: '🥒', cat: 'veggies' },
  { id: 40, name: 'Eggplant',           plu: '4186', emoji: '🍆', cat: 'veggies' },
  { id: 41, name: 'Cauliflower',        plu: '4135', emoji: '🥦', cat: 'veggies' },
  { id: 42, name: 'Celery',             plu: '4069', emoji: '🥬', cat: 'veggies' },
  { id: 43, name: 'Mushroom',           plu: '4299', emoji: '🍄', cat: 'veggies' },
  { id: 44, name: 'Leek',               plu: '4389', emoji: '🧅', cat: 'veggies' },
  { id: 45, name: 'Radish',             plu: '3346', emoji: '🌑', cat: 'veggies' },
  { id: 46, name: 'Beetroot',           plu: '3006', emoji: '🟣', cat: 'veggies' },
  { id: 47, name: 'Sweet Potato',       plu: '4072', emoji: '🍠', cat: 'veggies' },
  { id: 48, name: 'Cabbage',            plu: '3474', emoji: '🥬', cat: 'veggies' },
  { id: 49, name: 'Peas',               plu: '3143', emoji: '🟢', cat: 'veggies' },
  { id: 50, name: 'Green Beans',        plu: '3018', emoji: '🌿', cat: 'veggies' },

  /* ── BAKERY ── */
  { id: 51, name: 'White Baguette',    plu: '2001', emoji: '🥖', cat: 'bakery'  },
  { id: 52, name: 'Whole-Grain Loaf',  plu: '2002', emoji: '🍞', cat: 'bakery'  },
  { id: 53, name: 'Croissant',         plu: '2003', emoji: '🥐', cat: 'bakery'  },
  { id: 54, name: 'Pretzel',           plu: '2004', emoji: '🥨', cat: 'bakery'  },
  { id: 55, name: 'Bagel',             plu: '2005', emoji: '🥯', cat: 'bakery'  },
  { id: 56, name: 'Ciabatta',          plu: '2006', emoji: '🍞', cat: 'bakery'  },
  { id: 57, name: 'Sourdough Loaf',    plu: '2007', emoji: '🍞', cat: 'bakery'  },
  { id: 58, name: 'Rye Bread',         plu: '2008', emoji: '🍞', cat: 'bakery'  },
  { id: 59, name: 'Dinner Roll',       plu: '2009', emoji: '🥐', cat: 'bakery'  },
  { id: 60, name: 'Muffin (Blueberry)',plu: '2010', emoji: '🧁', cat: 'bakery'  },
  { id: 61, name: 'Donut (Glazed)',    plu: '2011', emoji: '🍩', cat: 'bakery'  },
  { id: 62, name: 'Cinnamon Roll',     plu: '2012', emoji: '🌀', cat: 'bakery'  },
  { id: 63, name: 'Focaccia',          plu: '2013', emoji: '🥖', cat: 'bakery'  },
  { id: 64, name: 'Brioche',           plu: '2014', emoji: '🍞', cat: 'bakery'  },
  { id: 65, name: 'Pain au Chocolat',  plu: '2015', emoji: '🥐', cat: 'bakery'  },

  /* ── DAIRY ── */
  { id: 66, name: 'Whole Milk 1L',     plu: '5001', emoji: '🥛', cat: 'dairy'   },
  { id: 67, name: 'Skimmed Milk 1L',   plu: '5002', emoji: '🥛', cat: 'dairy'   },
  { id: 68, name: 'Butter 250g',       plu: '5010', emoji: '🧈', cat: 'dairy'   },
  { id: 69, name: 'Greek Yogurt',      plu: '5015', emoji: '🍦', cat: 'dairy'   },
  { id: 70, name: 'Cream Cheese',      plu: '5020', emoji: '🧀', cat: 'dairy'   },
  { id: 71, name: 'Sour Cream',        plu: '5025', emoji: '🍶', cat: 'dairy'   },
  { id: 72, name: 'Heavy Cream',       plu: '5030', emoji: '🥛', cat: 'dairy'   },
  { id: 73, name: 'Eggs (6-pack)',      plu: '5040', emoji: '🥚', cat: 'dairy'   },
  { id: 74, name: 'Eggs (12-pack)',     plu: '5041', emoji: '🥚', cat: 'dairy'   },

  /* ── MEAT ── */
  { id: 75, name: 'Chicken Breast',    plu: '6001', emoji: '🍗', cat: 'meat'    },
  { id: 76, name: 'Chicken Legs',      plu: '6002', emoji: '🍖', cat: 'meat'    },
  { id: 77, name: 'Ground Beef',       plu: '6010', emoji: '🥩', cat: 'meat'    },
  { id: 78, name: 'Beef Steak',        plu: '6011', emoji: '🥩', cat: 'meat'    },
  { id: 79, name: 'Pork Chops',        plu: '6020', emoji: '🍖', cat: 'meat'    },
  { id: 80, name: 'Bacon',             plu: '6025', emoji: '🥓', cat: 'meat'    },
  { id: 81, name: 'Sausages',          plu: '6030', emoji: '🌭', cat: 'meat'    },
  { id: 82, name: 'Salmon Fillet',     plu: '6050', emoji: '🐟', cat: 'meat'    },
  { id: 83, name: 'Tuna Steak',        plu: '6051', emoji: '🐟', cat: 'meat'    },
  { id: 84, name: 'Turkey Breast',     plu: '6005', emoji: '🦃', cat: 'meat'    },

  /* ── DELI ── */
  { id: 85, name: 'Cheddar Cheese',    plu: '7001', emoji: '🧀', cat: 'deli'    },
  { id: 86, name: 'Gouda Cheese',      plu: '7002', emoji: '🧀', cat: 'deli'    },
  { id: 87, name: 'Brie',              plu: '7005', emoji: '🧀', cat: 'deli'    },
  { id: 88, name: 'Ham (Sliced)',       plu: '7010', emoji: '🍖', cat: 'deli'    },
  { id: 89, name: 'Salami',            plu: '7012', emoji: '🍕', cat: 'deli'    },
  { id: 90, name: 'Pepperoni',         plu: '7013', emoji: '🍕', cat: 'deli'    },
  { id: 91, name: 'Hummus',            plu: '7020', emoji: '🥣', cat: 'deli'    },
  { id: 92, name: 'Tzatziki',          plu: '7021', emoji: '🥣', cat: 'deli'    },

  /* ── FROZEN ── */
  { id: 93, name: 'Frozen Pizza',      plu: '8001', emoji: '🍕', cat: 'frozen'  },
  { id: 94, name: 'Ice Cream Tub',     plu: '8010', emoji: '🍨', cat: 'frozen'  },
  { id: 95, name: 'Frozen Chips',      plu: '8020', emoji: '🍟', cat: 'frozen'  },
  { id: 96, name: 'Frozen Peas',       plu: '8030', emoji: '🟢', cat: 'frozen'  },
  { id: 97, name: 'Fish Fingers',      plu: '8040', emoji: '🐟', cat: 'frozen'  },
  { id: 98, name: 'Frozen Waffles',    plu: '8050', emoji: '🧇', cat: 'frozen'  },

  /* ── SNACKS ── */
  { id: 99,  name: 'Chocolate Bar',    plu: '9001', emoji: '🍫', cat: 'snacks'  },
  { id: 100, name: 'Potato Crisps',    plu: '9002', emoji: '🥔', cat: 'snacks'  },
  { id: 101, name: 'Pretzels (Bag)',   plu: '9003', emoji: '🥨', cat: 'snacks'  },
  { id: 102, name: 'Mixed Nuts',       plu: '9010', emoji: '🥜', cat: 'snacks'  },
  { id: 103, name: 'Granola Bar',      plu: '9015', emoji: '🍫', cat: 'snacks'  },
  { id: 104, name: 'Popcorn Bag',      plu: '9020', emoji: '🍿', cat: 'snacks'  },
  { id: 105, name: 'Dried Mango',      plu: '9025', emoji: '🥭', cat: 'snacks'  },
];
